### ISSUE TITLE
Data loss

### ISSUE THREAD

**Issue by ncadou** [sethyuan/logseq-plugin-luckysheet#10]
Hi! I've happily been using the Luckysheet Logseq plugin, which I like very much apart from one thing: this plugin tends to lose data.

I understand that for performance reasons it writes to temporary files and syncs with the child block markdown only on the next app start, but this process is not entirely reliable and I have lost hours of work on a few occasions. Plus I sync my Logseq graph on multiple devices, and Luckysheets aren't part of that sync unless I close and reopen Logseq everytime, which is cumbersome and slow.

How about a "save" button that syncs with the child block markdown when clicked? This way the plugin keeps its current performance profile, and would also provide data safety.

**Comment by sethyuan** [comment]
Sorry to hear about the data loss! I think it's has something to do with the syncing between multiple devices, since the buffered data is stored only where you made the edits. Anyway, any third party syncing may cause data loss in Logseq and the save delaying to the next start may just make it worse.

The idea of a save button is great, I can implement that. BTW, I hear that Logseq will provide better asset read/write functionalities soon, and writes can be hugely improved by then.

**Comment by sethyuan** [comment]
@ncadou FYI, the save button is implemented.

**Comment by ncadou** [comment]
Yeah, it's possible it's sync related, although most of the time it's unidirectional as apart from rare exceptions I edit my graph from just one machine.

Thanks for the save button, works perfectly!

**Comment by darioceccoli** [comment]
To me the data loss is caused by switching between graphs.
Steps to reproduce:
- Open Graph 1
- Edit a LuckySheet on Graph 1
- Swith to Graph 2
- Restart Logseq
- Open Graph 1 -> Changes on LuckySheet on Graph 1 are lost 😱

Thanks for the save button by the way, it's very useful to mitigate the issue!

**Comment by ncadou** [comment]
That's interesting. I don't remember the exact sequence but I have indeed been editing multiple spreadsheets at the time the data losses occurred.

**Comment by sethyuan** [comment]
Write stability can be solved once Logseq releases the new asset API, meanwhile, please remember to use the save button. 😂

**Comment by darrellhansen** [comment]
Can luckysheets be used in templates? It would need to create a new luckysheet instance when the template is used.
